Set-Alias ..  Step-Up
Set-Alias up  Step-Up
Set-Alias gup Get-Up
Set-Alias xup Get-Ancestors
Set-Alias xpa Expand-Path
Set-Alias cd- Undo-Location
Set-Alias cd+ Redo-Location
Set-Alias cd: Switch-LocationPart
Set-Alias cdr Set-RecentLocation
Set-Alias cdf Set-FrecentLocation
Set-Alias dirs Get-Stack
Set-Alias dirsc Clear-Stack
Set-Alias setocd Set-CdExtrasOption
Set-Alias mark Add-Bookmark
Set-Alias unmark Remove-Bookmark
Set-Alias '~' Undo-Location
Set-Alias '~~' Redo-Location

Set-Item Alias:cd Set-LocationEx
