name: Run tests
on: push

jobs:
  build:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run the tests
        run: |
          . ./cd-extras/public/_Classes.ps1
          md ./_reports
          Import-Module Pester
          cd tests
          Invoke-Pester ./cd-extras.Tests.ps1 -EnableExit -CodeCoverage ../cd-extras/private/*.ps1,../cd-extras/public/*.ps1 -CodeCoverageOutputFile ../_reports/coverage.xml -OutputFile ../_reports/testresults.xml
        shell: pwsh

      # run the tests again on Windows, this time in PowerShell v5
      - name: Run the tests (Powershell v5)
        if: matrix.os == 'windows-latest'
        run: |
          . ./cd-extras/public/_Classes.ps1
          md ./_reports -ea Ignore
          Import-Module Pester
          Invoke-Pester ./tests/cd-extras.Tests.ps1 -EnableExit -OutputFile ./_reports/testresults_powershell.xml
        shell: powershell

      - name: Upload test report
        uses: actions/upload-artifact@master
        with:
          name: Test Report (${{ matrix.os }})
          path: _reports

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./_reports/coverage.xml
          flags: ${{ runner.os }}
